
package com.proto.server.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-08-31T11:44:08.024-05:00
 * Generated source version: 3.1.10
 * 
 */
public final class AdminUsuarios_AdminUsuariosPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.server.proto.com/", "AdminUsuarios");

    private AdminUsuarios_AdminUsuariosPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AdminUsuarios_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AdminUsuarios_Service ss = new AdminUsuarios_Service(wsdlURL, SERVICE_NAME);
        AdminUsuarios port = ss.getAdminUsuariosPort();  
        
        {
        System.out.println("Invoking consultaUsuario...");
        com.proto.server.ws.ConsultaUsuario _consultaUsuario_parameters = new com.proto.server.ws.ConsultaUsuario();
        _consultaUsuario_parameters.setUsuario("Usuario1269783195");
        java.lang.String _consultaUsuario_username = "_consultaUsuario_username-946419702";
        java.lang.String _consultaUsuario_password = "_consultaUsuario_password1499506673";
        com.proto.server.ws.ConsultaUsuarioResponse _consultaUsuario__return = port.consultaUsuario(_consultaUsuario_parameters, _consultaUsuario_username, _consultaUsuario_password);
        System.out.println("consultaUsuario.result=" + _consultaUsuario__return);


        }
        {
        System.out.println("Invoking crearUsuario...");
        com.proto.server.ws.CrearUsuario _crearUsuario_parameters = new com.proto.server.ws.CrearUsuario();
        _crearUsuario_parameters.setNombres("Nombres-2020492564");
        _crearUsuario_parameters.setApellidos("Apellidos3329241");
        _crearUsuario_parameters.setNroDocumento("NroDocumento1595125595");
        _crearUsuario_parameters.setNroCelular("NroCelular1451445723");
        _crearUsuario_parameters.setEMail("EMail1066963127");
        _crearUsuario_parameters.setUsuario("Usuario1967345694");
        _crearUsuario_parameters.setContrasena("Contrasena-1371708090");
        _crearUsuario_parameters.setCodigoConcesionario("CodigoConcesionario-1895527356");
        _crearUsuario_parameters.setCodigoSiic("CodigoSiic-826302202");
        _crearUsuario_parameters.setPerfilId(Integer.valueOf(-1337887662));
        java.lang.String _crearUsuario_username = "_crearUsuario_username2118024387";
        java.lang.String _crearUsuario_password = "_crearUsuario_password1397486999";
        com.proto.server.ws.CrearUsuarioResponse _crearUsuario__return = port.crearUsuario(_crearUsuario_parameters, _crearUsuario_username, _crearUsuario_password);
        System.out.println("crearUsuario.result=" + _crearUsuario__return);


        }
        {
        System.out.println("Invoking obtenerRoles...");
        com.proto.server.ws.ObtenerRoles _obtenerRoles_parameters = new com.proto.server.ws.ObtenerRoles();
        java.lang.String _obtenerRoles_username = "_obtenerRoles_username-207983568";
        java.lang.String _obtenerRoles_password = "_obtenerRoles_password-687215183";
        com.proto.server.ws.ObtenerRolesResponse _obtenerRoles__return = port.obtenerRoles(_obtenerRoles_parameters, _obtenerRoles_username, _obtenerRoles_password);
        System.out.println("obtenerRoles.result=" + _obtenerRoles__return);


        }
        {
        System.out.println("Invoking modificarUsuario...");
        com.proto.server.ws.ModificarUsuario _modificarUsuario_parameters = new com.proto.server.ws.ModificarUsuario();
        _modificarUsuario_parameters.setNombres("Nombres-2134540538");
        _modificarUsuario_parameters.setApellidos("Apellidos1701798430");
        _modificarUsuario_parameters.setNroDocumento("NroDocumento-1997362041");
        _modificarUsuario_parameters.setNroCelular("NroCelular1606867958");
        _modificarUsuario_parameters.setEMail("EMail2134543821");
        _modificarUsuario_parameters.setUsuario("Usuario-1068464695");
        _modificarUsuario_parameters.setContrasena("Contrasena-358665523");
        _modificarUsuario_parameters.setCodigoConcesionario("CodigoConcesionario-580132939");
        _modificarUsuario_parameters.setCodigoSiic("CodigoSiic1459377913");
        _modificarUsuario_parameters.setPerfilId(Integer.valueOf(-1529373139));
        java.lang.String _modificarUsuario_username = "_modificarUsuario_username864523750";
        java.lang.String _modificarUsuario_password = "_modificarUsuario_password-921460216";
        com.proto.server.ws.ModificarUsuarioResponse _modificarUsuario__return = port.modificarUsuario(_modificarUsuario_parameters, _modificarUsuario_username, _modificarUsuario_password);
        System.out.println("modificarUsuario.result=" + _modificarUsuario__return);


        }
        {
        System.out.println("Invoking inactivarActivarUsuario...");
        com.proto.server.ws.InactivarActivarUsuario _inactivarActivarUsuario_parameters = new com.proto.server.ws.InactivarActivarUsuario();
        _inactivarActivarUsuario_parameters.setUsuario("Usuario20983136");
        _inactivarActivarUsuario_parameters.setAccion("Accion102530255");
        java.lang.String _inactivarActivarUsuario_username = "_inactivarActivarUsuario_username-1727616561";
        java.lang.String _inactivarActivarUsuario_password = "_inactivarActivarUsuario_password582726253";
        com.proto.server.ws.InactivarActivarUsuarioResponse _inactivarActivarUsuario__return = port.inactivarActivarUsuario(_inactivarActivarUsuario_parameters, _inactivarActivarUsuario_username, _inactivarActivarUsuario_password);
        System.out.println("inactivarActivarUsuario.result=" + _inactivarActivarUsuario__return);


        }
        {
        System.out.println("Invoking cambiarContrasena...");
        com.proto.server.ws.CambiarContrasena _cambiarContrasena_parameters = new com.proto.server.ws.CambiarContrasena();
        _cambiarContrasena_parameters.setUsuario("Usuario312105697");
        _cambiarContrasena_parameters.setContrasena("Contrasena1386181027");
        java.lang.String _cambiarContrasena_username = "_cambiarContrasena_username-460787250";
        java.lang.String _cambiarContrasena_password = "_cambiarContrasena_password-196747538";
        com.proto.server.ws.CambiarContrasenaResponse _cambiarContrasena__return = port.cambiarContrasena(_cambiarContrasena_parameters, _cambiarContrasena_username, _cambiarContrasena_password);
        System.out.println("cambiarContrasena.result=" + _cambiarContrasena__return);


        }

        System.exit(0);
    }

}
