package com.proto.server.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-08-31T11:44:08.085-05:00
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "AdminUsuarios", 
                  wsdlLocation = "http://10.75.30.16:8080/servWsRs/AdminUsuarios?wsdl",
                  targetNamespace = "http://ws.server.proto.com/") 
public class AdminUsuarios_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.server.proto.com/", "AdminUsuarios");
    public final static QName AdminUsuariosPort = new QName("http://ws.server.proto.com/", "AdminUsuariosPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.75.30.16:8080/servWsRs/AdminUsuarios?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AdminUsuarios_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.75.30.16:8080/servWsRs/AdminUsuarios?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AdminUsuarios_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AdminUsuarios_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdminUsuarios_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public AdminUsuarios_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AdminUsuarios_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AdminUsuarios_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns AdminUsuarios
     */
    @WebEndpoint(name = "AdminUsuariosPort")
    public AdminUsuarios getAdminUsuariosPort() {
        return super.getPort(AdminUsuariosPort, AdminUsuarios.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdminUsuarios
     */
    @WebEndpoint(name = "AdminUsuariosPort")
    public AdminUsuarios getAdminUsuariosPort(WebServiceFeature... features) {
        return super.getPort(AdminUsuariosPort, AdminUsuarios.class, features);
    }

}
