package com.proto.server.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-08-31T11:44:08.080-05:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://ws.server.proto.com/", name = "AdminUsuarios")
@XmlSeeAlso({ObjectFactory.class, entidad.ws.server.proto.com.resultado.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AdminUsuarios {

    @WebMethod(operationName = "consulta-usuario")
    @WebResult(name = "consulta-usuarioResponse", targetNamespace = "http://ws.server.proto.com/", partName = "parameters")
    public ConsultaUsuarioResponse consultaUsuario(
        @WebParam(partName = "parameters", name = "consulta-usuario", targetNamespace = "http://ws.server.proto.com/")
        ConsultaUsuario parameters,
        @WebParam(partName = "username", name = "username", targetNamespace = "http://ws.server.proto.com/", header = true)
        java.lang.String username,
        @WebParam(partName = "password", name = "password", targetNamespace = "http://ws.server.proto.com/", header = true)
        java.lang.String password
    );

    @WebMethod(operationName = "crear-usuario")
    @WebResult(name = "crear-usuarioResponse", targetNamespace = "http://ws.server.proto.com/", partName = "parameters")
    public CrearUsuarioResponse crearUsuario(
        @WebParam(partName = "parameters", name = "crear-usuario", targetNamespace = "http://ws.server.proto.com/")
        CrearUsuario parameters,
        @WebParam(partName = "username", name = "username", targetNamespace = "http://ws.server.proto.com/", header = true)
        java.lang.String username,
        @WebParam(partName = "password", name = "password", targetNamespace = "http://ws.server.proto.com/", header = true)
        java.lang.String password
    );

    @WebMethod(operationName = "obtener-roles")
    @WebResult(name = "obtener-rolesResponse", targetNamespace = "http://ws.server.proto.com/", partName = "parameters")
    public ObtenerRolesResponse obtenerRoles(
        @WebParam(partName = "parameters", name = "obtener-roles", targetNamespace = "http://ws.server.proto.com/")
        ObtenerRoles parameters,
        @WebParam(partName = "username", name = "username", targetNamespace = "http://ws.server.proto.com/", header = true)
        java.lang.String username,
        @WebParam(partName = "password", name = "password", targetNamespace = "http://ws.server.proto.com/", header = true)
        java.lang.String password
    );

    @WebMethod(operationName = "modificar-usuario")
    @WebResult(name = "modificar-usuarioResponse", targetNamespace = "http://ws.server.proto.com/", partName = "parameters")
    public ModificarUsuarioResponse modificarUsuario(
        @WebParam(partName = "parameters", name = "modificar-usuario", targetNamespace = "http://ws.server.proto.com/")
        ModificarUsuario parameters,
        @WebParam(partName = "username", name = "username", targetNamespace = "http://ws.server.proto.com/", header = true)
        java.lang.String username,
        @WebParam(partName = "password", name = "password", targetNamespace = "http://ws.server.proto.com/", header = true)
        java.lang.String password
    );

    @WebMethod(operationName = "inactivar-activar-usuario")
    @WebResult(name = "inactivar-activar-usuarioResponse", targetNamespace = "http://ws.server.proto.com/", partName = "parameters")
    public InactivarActivarUsuarioResponse inactivarActivarUsuario(
        @WebParam(partName = "parameters", name = "inactivar-activar-usuario", targetNamespace = "http://ws.server.proto.com/")
        InactivarActivarUsuario parameters,
        @WebParam(partName = "username", name = "username", targetNamespace = "http://ws.server.proto.com/", header = true)
        java.lang.String username,
        @WebParam(partName = "password", name = "password", targetNamespace = "http://ws.server.proto.com/", header = true)
        java.lang.String password
    );

    @WebMethod(operationName = "cambiar-contrasena")
    @WebResult(name = "cambiar-contrasenaResponse", targetNamespace = "http://ws.server.proto.com/", partName = "parameters")
    public CambiarContrasenaResponse cambiarContrasena(
        @WebParam(partName = "parameters", name = "cambiar-contrasena", targetNamespace = "http://ws.server.proto.com/")
        CambiarContrasena parameters,
        @WebParam(partName = "username", name = "username", targetNamespace = "http://ws.server.proto.com/", header = true)
        java.lang.String username,
        @WebParam(partName = "password", name = "password", targetNamespace = "http://ws.server.proto.com/", header = true)
        java.lang.String password
    );
}
