
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.proto.server.ws;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-08-31T11:44:08.071-05:00
 * Generated source version: 3.1.10
 * 
 */

@javax.jws.WebService(
                      serviceName = "AdminUsuarios",
                      portName = "AdminUsuariosPort",
                      targetNamespace = "http://ws.server.proto.com/",
                      wsdlLocation = "http://10.75.30.16:8080/servWsRs/AdminUsuarios?wsdl",
                      endpointInterface = "com.proto.server.ws.AdminUsuarios")
                      
public class AdminUsuariosPortImpl implements AdminUsuarios {

    private static final Logger LOG = Logger.getLogger(AdminUsuariosPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.proto.server.ws.AdminUsuarios#consultaUsuario(com.proto.server.ws.ConsultaUsuario parameters, java.lang.String username, java.lang.String password)*
     */
    public com.proto.server.ws.ConsultaUsuarioResponse consultaUsuario(ConsultaUsuario parameters, java.lang.String username, java.lang.String password) { 
        LOG.info("Executing operation consultaUsuario");
        System.out.println(parameters);
        System.out.println(username);
        System.out.println(password);
        try {
            com.proto.server.ws.ConsultaUsuarioResponse _return = new com.proto.server.ws.ConsultaUsuarioResponse();
            entidad.ws.server.proto.com.resultado.Resultado _returnXmlResultado = new entidad.ws.server.proto.com.resultado.Resultado();
            _returnXmlResultado.setCodigo("Codigo821100471");
            _returnXmlResultado.setMensaje("Mensaje-1698178609");
            _return.setXmlResultado(_returnXmlResultado);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.proto.server.ws.AdminUsuarios#crearUsuario(com.proto.server.ws.CrearUsuario parameters, java.lang.String username, java.lang.String password)*
     */
    public com.proto.server.ws.CrearUsuarioResponse crearUsuario(CrearUsuario parameters, java.lang.String username, java.lang.String password) { 
        LOG.info("Executing operation crearUsuario");
        System.out.println(parameters);
        System.out.println(username);
        System.out.println(password);
        try {
            com.proto.server.ws.CrearUsuarioResponse _return = new com.proto.server.ws.CrearUsuarioResponse();
            entidad.ws.server.proto.com.resultado.Resultado _returnXmlResultado = new entidad.ws.server.proto.com.resultado.Resultado();
            _returnXmlResultado.setCodigo("Codigo543392234");
            _returnXmlResultado.setMensaje("Mensaje1718905474");
            _return.setXmlResultado(_returnXmlResultado);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.proto.server.ws.AdminUsuarios#obtenerRoles(com.proto.server.ws.ObtenerRoles parameters, java.lang.String username, java.lang.String password)*
     */
    public com.proto.server.ws.ObtenerRolesResponse obtenerRoles(ObtenerRoles parameters, java.lang.String username, java.lang.String password) { 
        LOG.info("Executing operation obtenerRoles");
        System.out.println(parameters);
        System.out.println(username);
        System.out.println(password);
        try {
            com.proto.server.ws.ObtenerRolesResponse _return = new com.proto.server.ws.ObtenerRolesResponse();
            _return.setXmlRegistros("XmlRegistros2012025618");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.proto.server.ws.AdminUsuarios#modificarUsuario(com.proto.server.ws.ModificarUsuario parameters, java.lang.String username, java.lang.String password)*
     */
    public com.proto.server.ws.ModificarUsuarioResponse modificarUsuario(ModificarUsuario parameters, java.lang.String username, java.lang.String password) { 
        LOG.info("Executing operation modificarUsuario");
        System.out.println(parameters);
        System.out.println(username);
        System.out.println(password);
        try {
            com.proto.server.ws.ModificarUsuarioResponse _return = new com.proto.server.ws.ModificarUsuarioResponse();
            entidad.ws.server.proto.com.resultado.Resultado _returnXmlResultado = new entidad.ws.server.proto.com.resultado.Resultado();
            _returnXmlResultado.setCodigo("Codigo-1141483852");
            _returnXmlResultado.setMensaje("Mensaje2075329438");
            _return.setXmlResultado(_returnXmlResultado);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.proto.server.ws.AdminUsuarios#inactivarActivarUsuario(com.proto.server.ws.InactivarActivarUsuario parameters, java.lang.String username, java.lang.String password)*
     */
    public com.proto.server.ws.InactivarActivarUsuarioResponse inactivarActivarUsuario(InactivarActivarUsuario parameters, java.lang.String username, java.lang.String password) { 
        LOG.info("Executing operation inactivarActivarUsuario");
        System.out.println(parameters);
        System.out.println(username);
        System.out.println(password);
        try {
            com.proto.server.ws.InactivarActivarUsuarioResponse _return = new com.proto.server.ws.InactivarActivarUsuarioResponse();
            entidad.ws.server.proto.com.resultado.Resultado _returnXmlResultado = new entidad.ws.server.proto.com.resultado.Resultado();
            _returnXmlResultado.setCodigo("Codigo-1828141645");
            _returnXmlResultado.setMensaje("Mensaje-115189533");
            _return.setXmlResultado(_returnXmlResultado);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.proto.server.ws.AdminUsuarios#cambiarContrasena(com.proto.server.ws.CambiarContrasena parameters, java.lang.String username, java.lang.String password)*
     */
    public com.proto.server.ws.CambiarContrasenaResponse cambiarContrasena(CambiarContrasena parameters, java.lang.String username, java.lang.String password) { 
        LOG.info("Executing operation cambiarContrasena");
        System.out.println(parameters);
        System.out.println(username);
        System.out.println(password);
        try {
            com.proto.server.ws.CambiarContrasenaResponse _return = new com.proto.server.ws.CambiarContrasenaResponse();
            entidad.ws.server.proto.com.resultado.Resultado _returnXmlResultado = new entidad.ws.server.proto.com.resultado.Resultado();
            _returnXmlResultado.setCodigo("Codigo1339355437");
            _returnXmlResultado.setMensaje("Mensaje-1445342775");
            _return.setXmlResultado(_returnXmlResultado);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
