package com.vortexbird.sentinel.modelo;
// Generated Oct 15, 2016 4:43:12 PM by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * SegAuditoria generated by hbm2java
 */
public class SegAuditoria  implements java.io.Serializable {


     private Long autCodigo;
     private SegUsuario segUsuario;
     private String tabla;
     private Long codRegistro;
     private String campo;
     private String tipo;
     private Date fecha;
     private String valorAnterior;
     private String valorNuevo;

    public SegAuditoria() {
    }

	
    public SegAuditoria(Long autCodigo) {
        this.autCodigo = autCodigo;
    }
    public SegAuditoria(Long autCodigo, SegUsuario segUsuario, String tabla, Long codRegistro, String campo, String tipo, Date fecha, String valorAnterior, String valorNuevo) {
       this.autCodigo = autCodigo;
       this.segUsuario = segUsuario;
       this.tabla = tabla;
       this.codRegistro = codRegistro;
       this.campo = campo;
       this.tipo = tipo;
       this.fecha = fecha;
       this.valorAnterior = valorAnterior;
       this.valorNuevo = valorNuevo;
    }
   
    public Long getAutCodigo() {
        return this.autCodigo;
    }
    
    public void setAutCodigo(Long autCodigo) {
        this.autCodigo = autCodigo;
    }
    public SegUsuario getSegUsuario() {
        return this.segUsuario;
    }
    
    public void setSegUsuario(SegUsuario segUsuario) {
        this.segUsuario = segUsuario;
    }
    public String getTabla() {
        return this.tabla;
    }
    
    public void setTabla(String tabla) {
        this.tabla = tabla;
    }
    public Long getCodRegistro() {
        return this.codRegistro;
    }
    
    public void setCodRegistro(Long codRegistro) {
        this.codRegistro = codRegistro;
    }
    public String getCampo() {
        return this.campo;
    }
    
    public void setCampo(String campo) {
        this.campo = campo;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getValorAnterior() {
        return this.valorAnterior;
    }
    
    public void setValorAnterior(String valorAnterior) {
        this.valorAnterior = valorAnterior;
    }
    public String getValorNuevo() {
        return this.valorNuevo;
    }
    
    public void setValorNuevo(String valorNuevo) {
        this.valorNuevo = valorNuevo;
    }




}


