package com.vortexbird.sentinel.modelo;
// Generated Oct 15, 2016 4:43:12 PM by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * SegCambioPass generated by hbm2java
 */
public class SegCambioPass  implements java.io.Serializable {


     private Long capCodigo;
     private SegUsuario segUsuario;
     private Date capFechaFin;
     private String capToken;
     private String capEstado;
     private Date capFechaIni;

    public SegCambioPass() {
    }

	
    public SegCambioPass(Long capCodigo) {
        this.capCodigo = capCodigo;
    }
    public SegCambioPass(Long capCodigo, SegUsuario segUsuario, Date capFechaFin, String capToken, String capEstado, Date capFechaIni) {
       this.capCodigo = capCodigo;
       this.segUsuario = segUsuario;
       this.capFechaFin = capFechaFin;
       this.capToken = capToken;
       this.capEstado = capEstado;
       this.capFechaIni = capFechaIni;
    }
   
    public Long getCapCodigo() {
        return this.capCodigo;
    }
    
    public void setCapCodigo(Long capCodigo) {
        this.capCodigo = capCodigo;
    }
    public SegUsuario getSegUsuario() {
        return this.segUsuario;
    }
    
    public void setSegUsuario(SegUsuario segUsuario) {
        this.segUsuario = segUsuario;
    }
    public Date getCapFechaFin() {
        return this.capFechaFin;
    }
    
    public void setCapFechaFin(Date capFechaFin) {
        this.capFechaFin = capFechaFin;
    }
    public String getCapToken() {
        return this.capToken;
    }
    
    public void setCapToken(String capToken) {
        this.capToken = capToken;
    }
    public String getCapEstado() {
        return this.capEstado;
    }
    
    public void setCapEstado(String capEstado) {
        this.capEstado = capEstado;
    }
    public Date getCapFechaIni() {
        return this.capFechaIni;
    }
    
    public void setCapFechaIni(Date capFechaIni) {
        this.capFechaIni = capFechaIni;
    }




}


