package com.vortexbird.sentinel.modelo;
// Generated Oct 15, 2016 4:43:12 PM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * SegGrupoOpcion generated by hbm2java
 */
public class SegGrupoOpcion  implements java.io.Serializable {


     private Long gruCodigo;
     private SegSistema segSistema;
     private SegGrupoOpcion segGrupoOpcion;
     private SegUsuario segUsuario;
     private String gruNombre;
     private String gruDescripcion;
     private String gruLlaveAcceso;
     private String gruEstadoRegistro;
     private String gruIcono;
     private Integer orden;
     private Set<SegGrupoOpcion> segGrupoOpcions = new HashSet<SegGrupoOpcion>(0);
     private Set<SegOpcion> segOpcions = new HashSet<SegOpcion>(0);
     private Set<SegPermiso> segPermisos = new HashSet<SegPermiso>(0);

    public SegGrupoOpcion() {
    }

	
    public SegGrupoOpcion(Long gruCodigo, SegSistema segSistema, String gruNombre, String gruEstadoRegistro, Integer orden) {
        this.gruCodigo = gruCodigo;
        this.segSistema = segSistema;
        this.gruNombre = gruNombre;
        this.gruEstadoRegistro = gruEstadoRegistro;
        this.orden = orden;
    }
    public SegGrupoOpcion(Long gruCodigo, SegSistema segSistema, SegGrupoOpcion segGrupoOpcion, SegUsuario segUsuario, String gruNombre, String gruDescripcion, String gruLlaveAcceso, String gruEstadoRegistro, String gruIcono, Set<SegGrupoOpcion> segGrupoOpcions, Set<SegOpcion> segOpcions, Set<SegPermiso> segPermisos, Integer orden) {
       this.gruCodigo = gruCodigo;
       this.segSistema = segSistema;
       this.segGrupoOpcion = segGrupoOpcion;
       this.segUsuario = segUsuario;
       this.gruNombre = gruNombre;
       this.gruDescripcion = gruDescripcion;
       this.gruLlaveAcceso = gruLlaveAcceso;
       this.gruEstadoRegistro = gruEstadoRegistro;
       this.gruIcono = gruIcono;
       this.segGrupoOpcions = segGrupoOpcions;
       this.segOpcions = segOpcions;
       this.segPermisos = segPermisos;
       this.orden = orden;
    }
   
    public Long getGruCodigo() {
        return this.gruCodigo;
    }
    
    public void setGruCodigo(Long gruCodigo) {
        this.gruCodigo = gruCodigo;
    }
    public SegSistema getSegSistema() {
        return this.segSistema;
    }
    
    public void setSegSistema(SegSistema segSistema) {
        this.segSistema = segSistema;
    }
    public SegGrupoOpcion getSegGrupoOpcion() {
        return this.segGrupoOpcion;
    }
    
    public void setSegGrupoOpcion(SegGrupoOpcion segGrupoOpcion) {
        this.segGrupoOpcion = segGrupoOpcion;
    }
    public SegUsuario getSegUsuario() {
        return this.segUsuario;
    }
    
    public void setSegUsuario(SegUsuario segUsuario) {
        this.segUsuario = segUsuario;
    }
    public String getGruNombre() {
        return this.gruNombre;
    }
    
    public void setGruNombre(String gruNombre) {
        this.gruNombre = gruNombre;
    }
    public String getGruDescripcion() {
        return this.gruDescripcion;
    }
    
    public void setGruDescripcion(String gruDescripcion) {
        this.gruDescripcion = gruDescripcion;
    }
    public String getGruLlaveAcceso() {
        return this.gruLlaveAcceso;
    }
    
    public void setGruLlaveAcceso(String gruLlaveAcceso) {
        this.gruLlaveAcceso = gruLlaveAcceso;
    }
    public String getGruEstadoRegistro() {
        return this.gruEstadoRegistro;
    }
    
    public void setGruEstadoRegistro(String gruEstadoRegistro) {
        this.gruEstadoRegistro = gruEstadoRegistro;
    }
    public String getGruIcono() {
        return this.gruIcono;
    }
    
    public void setGruIcono(String gruIcono) {
        this.gruIcono = gruIcono;
    }
    public Set<SegGrupoOpcion> getSegGrupoOpcions() {
        return this.segGrupoOpcions;
    }
    
    public void setSegGrupoOpcions(Set<SegGrupoOpcion> segGrupoOpcions) {
        this.segGrupoOpcions = segGrupoOpcions;
    }
    public Set<SegOpcion> getSegOpcions() {
        return this.segOpcions;
    }
    
    public void setSegOpcions(Set<SegOpcion> segOpcions) {
        this.segOpcions = segOpcions;
    }
    public Set<SegPermiso> getSegPermisos() {
        return this.segPermisos;
    }
    
    public void setSegPermisos(Set<SegPermiso> segPermisos) {
        this.segPermisos = segPermisos;
    }
	public Integer getOrden() {
		return orden;
	}
	public void setOrden(Integer orden) {
		this.orden = orden;
	}
    
}


