package com.vortexbird.sentinel.modelo;
// Generated Oct 15, 2016 4:43:12 PM by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * SegHistorialConstrasena generated by hbm2java
 */
public class SegHistorialConstrasena  implements java.io.Serializable {


     private Long hcoCodigo;
     private SegUsuario segUsuario;
     private String hcoConstrasena;
     private Date hcoFechaCambio;
     private String hcoDetalleCambio;

    public SegHistorialConstrasena() {
    }

	
    public SegHistorialConstrasena(Long hcoCodigo, SegUsuario segUsuario, String hcoConstrasena, Date hcoFechaCambio) {
        this.hcoCodigo = hcoCodigo;
        this.segUsuario = segUsuario;
        this.hcoConstrasena = hcoConstrasena;
        this.hcoFechaCambio = hcoFechaCambio;
    }
    public SegHistorialConstrasena(Long hcoCodigo, SegUsuario segUsuario, String hcoConstrasena, Date hcoFechaCambio, String hcoDetalleCambio) {
       this.hcoCodigo = hcoCodigo;
       this.segUsuario = segUsuario;
       this.hcoConstrasena = hcoConstrasena;
       this.hcoFechaCambio = hcoFechaCambio;
       this.hcoDetalleCambio = hcoDetalleCambio;
    }
   
    public Long getHcoCodigo() {
        return this.hcoCodigo;
    }
    
    public void setHcoCodigo(Long hcoCodigo) {
        this.hcoCodigo = hcoCodigo;
    }
    public SegUsuario getSegUsuario() {
        return this.segUsuario;
    }
    
    public void setSegUsuario(SegUsuario segUsuario) {
        this.segUsuario = segUsuario;
    }
    public String getHcoConstrasena() {
        return this.hcoConstrasena;
    }
    
    public void setHcoConstrasena(String hcoConstrasena) {
        this.hcoConstrasena = hcoConstrasena;
    }
    public Date getHcoFechaCambio() {
        return this.hcoFechaCambio;
    }
    
    public void setHcoFechaCambio(Date hcoFechaCambio) {
        this.hcoFechaCambio = hcoFechaCambio;
    }
    public String getHcoDetalleCambio() {
        return this.hcoDetalleCambio;
    }
    
    public void setHcoDetalleCambio(String hcoDetalleCambio) {
        this.hcoDetalleCambio = hcoDetalleCambio;
    }




}


