package com.vortexbird.sentinel.modelo;
// Generated Oct 15, 2016 4:43:12 PM by Hibernate Tools 4.0.0



/**
 * SegPermiso generated by hbm2java
 */
public class SegPermiso  implements java.io.Serializable {


     private Long perCodigo;
     private SegRol segRol;
     private SegOpcion segOpcion;
     private SegUsuario segUsuarioByUsuCodigo;
     private SegSistemaCia segSistemaCia;
     private SegUsuario segUsuarioByModUsuCodigo;
     private SegSucursal segSucursal;
     private SegGrupoOpcion segGrupoOpcion;
     private String perEstadoRegistro;

    public SegPermiso() {
    }

	
    public SegPermiso(Long perCodigo, String perEstadoRegistro) {
        this.perCodigo = perCodigo;
        this.perEstadoRegistro = perEstadoRegistro;
    }
    public SegPermiso(Long perCodigo, SegRol segRol, SegOpcion segOpcion, SegUsuario segUsuarioByUsuCodigo, SegSistemaCia segSistemaCia, SegUsuario segUsuarioByModUsuCodigo, SegSucursal segSucursal, SegGrupoOpcion segGrupoOpcion, String perEstadoRegistro) {
       this.perCodigo = perCodigo;
       this.segRol = segRol;
       this.segOpcion = segOpcion;
       this.segUsuarioByUsuCodigo = segUsuarioByUsuCodigo;
       this.segSistemaCia = segSistemaCia;
       this.segUsuarioByModUsuCodigo = segUsuarioByModUsuCodigo;
       this.segSucursal = segSucursal;
       this.segGrupoOpcion = segGrupoOpcion;
       this.perEstadoRegistro = perEstadoRegistro;
    }
   
    public Long getPerCodigo() {
        return this.perCodigo;
    }
    
    public void setPerCodigo(Long perCodigo) {
        this.perCodigo = perCodigo;
    }
    public SegRol getSegRol() {
        return this.segRol;
    }
    
    public void setSegRol(SegRol segRol) {
        this.segRol = segRol;
    }
    public SegOpcion getSegOpcion() {
        return this.segOpcion;
    }
    
    public void setSegOpcion(SegOpcion segOpcion) {
        this.segOpcion = segOpcion;
    }
    public SegUsuario getSegUsuarioByUsuCodigo() {
        return this.segUsuarioByUsuCodigo;
    }
    
    public void setSegUsuarioByUsuCodigo(SegUsuario segUsuarioByUsuCodigo) {
        this.segUsuarioByUsuCodigo = segUsuarioByUsuCodigo;
    }
    public SegSistemaCia getSegSistemaCia() {
        return this.segSistemaCia;
    }
    
    public void setSegSistemaCia(SegSistemaCia segSistemaCia) {
        this.segSistemaCia = segSistemaCia;
    }
    public SegUsuario getSegUsuarioByModUsuCodigo() {
        return this.segUsuarioByModUsuCodigo;
    }
    
    public void setSegUsuarioByModUsuCodigo(SegUsuario segUsuarioByModUsuCodigo) {
        this.segUsuarioByModUsuCodigo = segUsuarioByModUsuCodigo;
    }
    public SegSucursal getSegSucursal() {
        return this.segSucursal;
    }
    
    public void setSegSucursal(SegSucursal segSucursal) {
        this.segSucursal = segSucursal;
    }
    public SegGrupoOpcion getSegGrupoOpcion() {
        return this.segGrupoOpcion;
    }
    
    public void setSegGrupoOpcion(SegGrupoOpcion segGrupoOpcion) {
        this.segGrupoOpcion = segGrupoOpcion;
    }
    public String getPerEstadoRegistro() {
        return this.perEstadoRegistro;
    }
    
    public void setPerEstadoRegistro(String perEstadoRegistro) {
        this.perEstadoRegistro = perEstadoRegistro;
    }




}


