package com.vortexbird.sentinel.modelo;
// Generated Oct 15, 2016 4:43:12 PM by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * SegParametro generated by hbm2java
 */
public class SegParametro  implements java.io.Serializable {


     private Long parCodigo;
     private SegUsuario segUsuario;
     private String parNombre;
     private Double parValorNumerico;
     private String parValorAlfanumerico;
     private Date parValorFecha;
     private String parEstadoRegistro;

    public SegParametro() {
    }

	
    public SegParametro(Long parCodigo, String parNombre, String parEstadoRegistro) {
        this.parCodigo = parCodigo;
        this.parNombre = parNombre;
        this.parEstadoRegistro = parEstadoRegistro;
    }
    public SegParametro(Long parCodigo, SegUsuario segUsuario, String parNombre, Double parValorNumerico, String parValorAlfanumerico, Date parValorFecha, String parEstadoRegistro) {
       this.parCodigo = parCodigo;
       this.segUsuario = segUsuario;
       this.parNombre = parNombre;
       this.parValorNumerico = parValorNumerico;
       this.parValorAlfanumerico = parValorAlfanumerico;
       this.parValorFecha = parValorFecha;
       this.parEstadoRegistro = parEstadoRegistro;
    }
   
    public Long getParCodigo() {
        return this.parCodigo;
    }
    
    public void setParCodigo(Long parCodigo) {
        this.parCodigo = parCodigo;
    }
    public SegUsuario getSegUsuario() {
        return this.segUsuario;
    }
    
    public void setSegUsuario(SegUsuario segUsuario) {
        this.segUsuario = segUsuario;
    }
    public String getParNombre() {
        return this.parNombre;
    }
    
    public void setParNombre(String parNombre) {
        this.parNombre = parNombre;
    }
    public Double getParValorNumerico() {
        return this.parValorNumerico;
    }
    
    public void setParValorNumerico(Double parValorNumerico) {
        this.parValorNumerico = parValorNumerico;
    }
    public String getParValorAlfanumerico() {
        return this.parValorAlfanumerico;
    }
    
    public void setParValorAlfanumerico(String parValorAlfanumerico) {
        this.parValorAlfanumerico = parValorAlfanumerico;
    }
    public Date getParValorFecha() {
        return this.parValorFecha;
    }
    
    public void setParValorFecha(Date parValorFecha) {
        this.parValorFecha = parValorFecha;
    }
    public String getParEstadoRegistro() {
        return this.parEstadoRegistro;
    }
    
    public void setParEstadoRegistro(String parEstadoRegistro) {
        this.parEstadoRegistro = parEstadoRegistro;
    }




}


