package com.vortexbird.sentinel.modelo;
// Generated Oct 15, 2016 4:43:12 PM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * SegRol generated by hbm2java
 */
public class SegRol  implements java.io.Serializable {


     private Long rolCodigo;
     private SegUsuario segUsuario;
     private SegSistema segSistema;
     private String rolNombre;
     private String rolDescripcion;
     private Long rolDiasCaducidadPwd;
     private String rolEstadoRegistro;
     private String esAdmonDeAplicacion;
     private Set<SegPermiso> segPermisos = new HashSet<SegPermiso>(0);
     private Set<SegRolUsuario> segRolUsuarios = new HashSet<SegRolUsuario>(0);

    public SegRol() {
    }

	
    public SegRol(Long rolCodigo, SegSistema segSistema, String rolNombre, String rolEstadoRegistro) {
        this.rolCodigo = rolCodigo;
        this.segSistema = segSistema;
        this.rolNombre = rolNombre;
        this.rolEstadoRegistro = rolEstadoRegistro;
    }
    public SegRol(Long rolCodigo, SegUsuario segUsuario, SegSistema segSistema, String rolNombre, String rolDescripcion, Long rolDiasCaducidadPwd, String rolEstadoRegistro, Set<SegPermiso> segPermisos, Set<SegRolUsuario> segRolUsuarios) {
       this.rolCodigo = rolCodigo;
       this.segUsuario = segUsuario;
       this.segSistema = segSistema;
       this.rolNombre = rolNombre;
       this.rolDescripcion = rolDescripcion;
       this.rolDiasCaducidadPwd = rolDiasCaducidadPwd;
       this.rolEstadoRegistro = rolEstadoRegistro;
       this.segPermisos = segPermisos;
       this.segRolUsuarios = segRolUsuarios;
    }
   
    public Long getRolCodigo() {
        return this.rolCodigo;
    }
    
    public void setRolCodigo(Long rolCodigo) {
        this.rolCodigo = rolCodigo;
    }
    public SegUsuario getSegUsuario() {
        return this.segUsuario;
    }
    
    public void setSegUsuario(SegUsuario segUsuario) {
        this.segUsuario = segUsuario;
    }
    public SegSistema getSegSistema() {
        return this.segSistema;
    }
    
    public void setSegSistema(SegSistema segSistema) {
        this.segSistema = segSistema;
    }
    public String getRolNombre() {
        return this.rolNombre;
    }
    
    public void setRolNombre(String rolNombre) {
        this.rolNombre = rolNombre;
    }
    public String getRolDescripcion() {
        return this.rolDescripcion;
    }
    
    public void setRolDescripcion(String rolDescripcion) {
        this.rolDescripcion = rolDescripcion;
    }
    public Long getRolDiasCaducidadPwd() {
        return this.rolDiasCaducidadPwd;
    }
    
    public void setRolDiasCaducidadPwd(Long rolDiasCaducidadPwd) {
        this.rolDiasCaducidadPwd = rolDiasCaducidadPwd;
    }
    public String getRolEstadoRegistro() {
        return this.rolEstadoRegistro;
    }
    
    public void setRolEstadoRegistro(String rolEstadoRegistro) {
        this.rolEstadoRegistro = rolEstadoRegistro;
    }
    public Set<SegPermiso> getSegPermisos() {
        return this.segPermisos;
    }
    
    public void setSegPermisos(Set<SegPermiso> segPermisos) {
        this.segPermisos = segPermisos;
    }
    public Set<SegRolUsuario> getSegRolUsuarios() {
        return this.segRolUsuarios;
    }
    
    public void setSegRolUsuarios(Set<SegRolUsuario> segRolUsuarios) {
        this.segRolUsuarios = segRolUsuarios;
    }


	public String getEsAdmonDeAplicacion() {
		return esAdmonDeAplicacion;
	}


	public void setEsAdmonDeAplicacion(String esAdmonDeAplicacion) {
		this.esAdmonDeAplicacion = esAdmonDeAplicacion;
	}
    
}


