package com.vortexbird.sentinel.modelo;
// Generated Oct 15, 2016 4:43:12 PM by Hibernate Tools 4.0.0



/**
 * SegRolUsuario generated by hbm2java
 */
public class SegRolUsuario  implements java.io.Serializable {


     private Long rluCodigo;
     private SegUsuario segUsuarioBySegUsuarioUsuCodigo;
     private SegRol segRol;
     private SegUsuario segUsuarioByModUsuCodigo;
     private String rluEstadoRegistro;

    public SegRolUsuario() {
    }

	
    public SegRolUsuario(Long rluCodigo, SegUsuario segUsuarioBySegUsuarioUsuCodigo, SegRol segRol, String rluEstadoRegistro) {
        this.rluCodigo = rluCodigo;
        this.segUsuarioBySegUsuarioUsuCodigo = segUsuarioBySegUsuarioUsuCodigo;
        this.segRol = segRol;
        this.rluEstadoRegistro = rluEstadoRegistro;
    }
    public SegRolUsuario(Long rluCodigo, SegUsuario segUsuarioBySegUsuarioUsuCodigo, SegRol segRol, SegUsuario segUsuarioByModUsuCodigo, String rluEstadoRegistro) {
       this.rluCodigo = rluCodigo;
       this.segUsuarioBySegUsuarioUsuCodigo = segUsuarioBySegUsuarioUsuCodigo;
       this.segRol = segRol;
       this.segUsuarioByModUsuCodigo = segUsuarioByModUsuCodigo;
       this.rluEstadoRegistro = rluEstadoRegistro;
    }
   
    public Long getRluCodigo() {
        return this.rluCodigo;
    }
    
    public void setRluCodigo(Long rluCodigo) {
        this.rluCodigo = rluCodigo;
    }
    public SegUsuario getSegUsuarioBySegUsuarioUsuCodigo() {
        return this.segUsuarioBySegUsuarioUsuCodigo;
    }
    
    public void setSegUsuarioBySegUsuarioUsuCodigo(SegUsuario segUsuarioBySegUsuarioUsuCodigo) {
        this.segUsuarioBySegUsuarioUsuCodigo = segUsuarioBySegUsuarioUsuCodigo;
    }
    public SegRol getSegRol() {
        return this.segRol;
    }
    
    public void setSegRol(SegRol segRol) {
        this.segRol = segRol;
    }
    public SegUsuario getSegUsuarioByModUsuCodigo() {
        return this.segUsuarioByModUsuCodigo;
    }
    
    public void setSegUsuarioByModUsuCodigo(SegUsuario segUsuarioByModUsuCodigo) {
        this.segUsuarioByModUsuCodigo = segUsuarioByModUsuCodigo;
    }
    public String getRluEstadoRegistro() {
        return this.rluEstadoRegistro;
    }
    
    public void setRluEstadoRegistro(String rluEstadoRegistro) {
        this.rluEstadoRegistro = rluEstadoRegistro;
    }




}


