package com.vortexbird.sentinel.modelo;
// Generated Oct 15, 2016 4:43:12 PM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * SegSistema generated by hbm2java
 */
public class SegSistema  implements java.io.Serializable {


     private Long sisCodigo;
     private SegUsuario segUsuario;
     private String sisNombre;
     private String sisDescripcion;
     private String sisEstadoRegistro;
     private String sisUrl;
     private String sisIcono;
     private Set<SegSistemaCia> segSistemaCias = new HashSet<SegSistemaCia>(0);
     private Set<SegGrupoOpcion> segGrupoOpcions = new HashSet<SegGrupoOpcion>(0);
     private Set<SegRol> segRols = new HashSet<SegRol>(0);

    public SegSistema() {
    }

	
    public SegSistema(Long sisCodigo, String sisNombre, String sisEstadoRegistro) {
        this.sisCodigo = sisCodigo;
        this.sisNombre = sisNombre;
        this.sisEstadoRegistro = sisEstadoRegistro;
    }
    public SegSistema(Long sisCodigo, SegUsuario segUsuario, String sisNombre, String sisDescripcion, String sisEstadoRegistro, Set<SegSistemaCia> segSistemaCias, Set<SegGrupoOpcion> segGrupoOpcions, Set<SegRol> segRols) {
       this.sisCodigo = sisCodigo;
       this.segUsuario = segUsuario;
       this.sisNombre = sisNombre;
       this.sisDescripcion = sisDescripcion;
       this.sisEstadoRegistro = sisEstadoRegistro;
       this.segSistemaCias = segSistemaCias;
       this.segGrupoOpcions = segGrupoOpcions;
       this.segRols = segRols;
    }
   
    public Long getSisCodigo() {
        return this.sisCodigo;
    }
    
    public void setSisCodigo(Long sisCodigo) {
        this.sisCodigo = sisCodigo;
    }
    public SegUsuario getSegUsuario() {
        return this.segUsuario;
    }
    
    public void setSegUsuario(SegUsuario segUsuario) {
        this.segUsuario = segUsuario;
    }
    public String getSisNombre() {
        return this.sisNombre;
    }
    
    public void setSisNombre(String sisNombre) {
        this.sisNombre = sisNombre;
    }
    public String getSisDescripcion() {
        return this.sisDescripcion;
    }
    
    public void setSisDescripcion(String sisDescripcion) {
        this.sisDescripcion = sisDescripcion;
    }
    public String getSisEstadoRegistro() {
        return this.sisEstadoRegistro;
    }
    
    public void setSisEstadoRegistro(String sisEstadoRegistro) {
        this.sisEstadoRegistro = sisEstadoRegistro;
    }
    public Set<SegSistemaCia> getSegSistemaCias() {
        return this.segSistemaCias;
    }
    
    public void setSegSistemaCias(Set<SegSistemaCia> segSistemaCias) {
        this.segSistemaCias = segSistemaCias;
    }
    public Set<SegGrupoOpcion> getSegGrupoOpcions() {
        return this.segGrupoOpcions;
    }
    
    public void setSegGrupoOpcions(Set<SegGrupoOpcion> segGrupoOpcions) {
        this.segGrupoOpcions = segGrupoOpcions;
    }
    public Set<SegRol> getSegRols() {
        return this.segRols;
    }
    public void setSegRols(Set<SegRol> segRols) {
        this.segRols = segRols;
    }
	public String getSisUrl() {
		return sisUrl;
	}
	public void setSisUrl(String sisUrl) {
		this.sisUrl = sisUrl;
	}
	public String getSisIcono() {
		return sisIcono;
	}
	public void setSisIcono(String sisIcono) {
		this.sisIcono = sisIcono;
	}
}


