package com.vortexbird.sentinel.modelo;
// Generated Oct 15, 2016 4:43:12 PM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * SegSistemaCia generated by hbm2java
 */
public class SegSistemaCia  implements java.io.Serializable {


     private Long sicCodigo;
     private SegCompania segCompania;
     private SegUsuario segUsuario;
     private SegSistema segSistema;
     private String sicEstadoRegistro;
     private Set<SegPermiso> segPermisos = new HashSet<SegPermiso>(0);

    public SegSistemaCia() {
    }

	
    public SegSistemaCia(Long sicCodigo, SegCompania segCompania, SegSistema segSistema) {
        this.sicCodigo = sicCodigo;
        this.segCompania = segCompania;
        this.segSistema = segSistema;
    }
    public SegSistemaCia(Long sicCodigo, SegCompania segCompania, SegUsuario segUsuario, SegSistema segSistema, String sicEstadoRegistro, Set<SegPermiso> segPermisos) {
       this.sicCodigo = sicCodigo;
       this.segCompania = segCompania;
       this.segUsuario = segUsuario;
       this.segSistema = segSistema;
       this.sicEstadoRegistro = sicEstadoRegistro;
       this.segPermisos = segPermisos;
    }
   
    public Long getSicCodigo() {
        return this.sicCodigo;
    }
    
    public void setSicCodigo(Long sicCodigo) {
        this.sicCodigo = sicCodigo;
    }
    public SegCompania getSegCompania() {
        return this.segCompania;
    }
    
    public void setSegCompania(SegCompania segCompania) {
        this.segCompania = segCompania;
    }
    public SegUsuario getSegUsuario() {
        return this.segUsuario;
    }
    
    public void setSegUsuario(SegUsuario segUsuario) {
        this.segUsuario = segUsuario;
    }
    public SegSistema getSegSistema() {
        return this.segSistema;
    }
    
    public void setSegSistema(SegSistema segSistema) {
        this.segSistema = segSistema;
    }
    public String getSicEstadoRegistro() {
        return this.sicEstadoRegistro;
    }
    
    public void setSicEstadoRegistro(String sicEstadoRegistro) {
        this.sicEstadoRegistro = sicEstadoRegistro;
    }
    public Set<SegPermiso> getSegPermisos() {
        return this.segPermisos;
    }
    
    public void setSegPermisos(Set<SegPermiso> segPermisos) {
        this.segPermisos = segPermisos;
    }




}


