package com.vortexbird.sentinel.modelo;
// Generated Oct 15, 2016 4:43:12 PM by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SegUsuario generated by hbm2java
 */
public class SegUsuario  implements java.io.Serializable {


     private Long usuCodigo;
     private SegUsuario segUsuario;
     private String usuNombres;
     private String usuApellidos;
     private String usuLogin;
     private String usuConstrasena;
     private String usuEstadoRegistro;
     private String usuCodigoInterno;
     private Date usuUltmimaModificacionPass;
     private String usuCorreo;
     private Long usuIntentosFallidos;
     private Long usuCompaniaCiaCodigo;
     private String usuPrimerLoginSso;
     
     private Set<SegCompania> segCompanias = new HashSet<SegCompania>(0);
     private Set<SegPermiso> segPermisosForModUsuCodigo = new HashSet<SegPermiso>(0);
     private Set<SegSistemaCia> segSistemaCias = new HashSet<SegSistemaCia>(0);
     private Set<SegPermiso> segPermisosForUsuCodigo = new HashSet<SegPermiso>(0);
     private Set<SegRolUsuario> segRolUsuariosForSegUsuarioUsuCodigo = new HashSet<SegRolUsuario>(0);
     private Set<SegSistema> segSistemas = new HashSet<SegSistema>(0);
     private Set<SegHistorialConstrasena> segHistorialConstrasenas = new HashSet<SegHistorialConstrasena>(0);
     private Set<SegAuditoria> segAuditorias = new HashSet<SegAuditoria>(0);
     private Set<SegOpcion> segOpcions = new HashSet<SegOpcion>(0);
     private Set<SegSucursal> segSucursals = new HashSet<SegSucursal>(0);
     private Set<SegRolUsuario> segRolUsuariosForModUsuCodigo = new HashSet<SegRolUsuario>(0);
     private Set<SegCambioPass> segCambioPasses = new HashSet<SegCambioPass>(0);
     private Set<SegGrupoOpcion> segGrupoOpcions = new HashSet<SegGrupoOpcion>(0);
     private Set<SegUsuario> segUsuarios = new HashSet<SegUsuario>(0);
     private Set<SegRol> segRols = new HashSet<SegRol>(0);
     private Set<SegParametro> segParametros = new HashSet<SegParametro>(0);

    public SegUsuario() {
    }

	
    public SegUsuario(Long usuCodigo, String usuNombres, String usuApellidos, String usuLogin, String usuConstrasena, String usuEstadoRegistro, String usuCodigoInterno) {
        this.usuCodigo = usuCodigo;
        this.usuNombres = usuNombres;
        this.usuApellidos = usuApellidos;
        this.usuLogin = usuLogin;
        this.usuConstrasena = usuConstrasena;
        this.usuEstadoRegistro = usuEstadoRegistro;
        this.usuCodigoInterno = usuCodigoInterno;
    }
    public SegUsuario(Long usuCodigo, SegUsuario segUsuario, String usuNombres, String usuApellidos, String usuLogin, String usuConstrasena, String usuEstadoRegistro, String usuCodigoInterno, Date usuUltmimaModificacionPass, String usuCorreo, Long usuIntentosFallidos, Long usuCompaniaCiaCodigo, Set<SegCompania> segCompanias, Set<SegPermiso> segPermisosForModUsuCodigo, Set<SegSistemaCia> segSistemaCias, Set<SegPermiso> segPermisosForUsuCodigo, Set<SegRolUsuario> segRolUsuariosForSegUsuarioUsuCodigo, Set<SegSistema> segSistemas, Set<SegHistorialConstrasena> segHistorialConstrasenas, Set<SegAuditoria> segAuditorias, Set<SegOpcion> segOpcions, Set<SegSucursal> segSucursals, Set<SegRolUsuario> segRolUsuariosForModUsuCodigo, Set<SegCambioPass> segCambioPasses, Set<SegGrupoOpcion> segGrupoOpcions, Set<SegUsuario> segUsuarios, Set<SegRol> segRols, Set<SegParametro> segParametros) {
       this.usuCodigo = usuCodigo;
       this.segUsuario = segUsuario;
       this.usuNombres = usuNombres;
       this.usuApellidos = usuApellidos;
       this.usuLogin = usuLogin;
       this.usuConstrasena = usuConstrasena;
       this.usuEstadoRegistro = usuEstadoRegistro;
       this.usuCodigoInterno = usuCodigoInterno;
       this.usuUltmimaModificacionPass = usuUltmimaModificacionPass;
       this.usuCorreo = usuCorreo;
       this.usuIntentosFallidos = usuIntentosFallidos;
       this.usuCompaniaCiaCodigo = usuCompaniaCiaCodigo;
       this.segCompanias = segCompanias;
       this.segPermisosForModUsuCodigo = segPermisosForModUsuCodigo;
       this.segSistemaCias = segSistemaCias;
       this.segPermisosForUsuCodigo = segPermisosForUsuCodigo;
       this.segRolUsuariosForSegUsuarioUsuCodigo = segRolUsuariosForSegUsuarioUsuCodigo;
       this.segSistemas = segSistemas;
       this.segHistorialConstrasenas = segHistorialConstrasenas;
       this.segAuditorias = segAuditorias;
       this.segOpcions = segOpcions;
       this.segSucursals = segSucursals;
       this.segRolUsuariosForModUsuCodigo = segRolUsuariosForModUsuCodigo;
       this.segCambioPasses = segCambioPasses;
       this.segGrupoOpcions = segGrupoOpcions;
       this.segUsuarios = segUsuarios;
       this.segRols = segRols;
       this.segParametros = segParametros;
    }
   
    public Long getUsuCodigo() {
        return this.usuCodigo;
    }
    
    public void setUsuCodigo(Long usuCodigo) {
        this.usuCodigo = usuCodigo;
    }
    public SegUsuario getSegUsuario() {
        return this.segUsuario;
    }
    
    public void setSegUsuario(SegUsuario segUsuario) {
        this.segUsuario = segUsuario;
    }
    public String getUsuNombres() {
        return this.usuNombres;
    }
    
    public void setUsuNombres(String usuNombres) {
        this.usuNombres = usuNombres;
    }
    public String getUsuApellidos() {
        return this.usuApellidos;
    }
    
    public void setUsuApellidos(String usuApellidos) {
        this.usuApellidos = usuApellidos;
    }
    public String getUsuLogin() {
        return this.usuLogin;
    }
    
    public void setUsuLogin(String usuLogin) {
        this.usuLogin = usuLogin;
    }
    public String getUsuConstrasena() {
        return this.usuConstrasena;
    }
    
    public void setUsuConstrasena(String usuConstrasena) {
        this.usuConstrasena = usuConstrasena;
    }
    public String getUsuEstadoRegistro() {
        return this.usuEstadoRegistro;
    }
    
    public void setUsuEstadoRegistro(String usuEstadoRegistro) {
        this.usuEstadoRegistro = usuEstadoRegistro;
    }
    public String getUsuCodigoInterno() {
        return this.usuCodigoInterno;
    }
    
    public void setUsuCodigoInterno(String usuCodigoInterno) {
        this.usuCodigoInterno = usuCodigoInterno;
    }
    public Date getUsuUltmimaModificacionPass() {
        return this.usuUltmimaModificacionPass;
    }
    
    public void setUsuUltmimaModificacionPass(Date usuUltmimaModificacionPass) {
        this.usuUltmimaModificacionPass = usuUltmimaModificacionPass;
    }
    public String getUsuCorreo() {
        return this.usuCorreo;
    }
    
    public void setUsuCorreo(String usuCorreo) {
        this.usuCorreo = usuCorreo;
    }
    public Long getUsuIntentosFallidos() {
        return this.usuIntentosFallidos;
    }
    
    public void setUsuIntentosFallidos(Long usuIntentosFallidos) {
        this.usuIntentosFallidos = usuIntentosFallidos;
    }
    public Long getUsuCompaniaCiaCodigo() {
        return this.usuCompaniaCiaCodigo;
    }
    
    public void setUsuCompaniaCiaCodigo(Long usuCompaniaCiaCodigo) {
        this.usuCompaniaCiaCodigo = usuCompaniaCiaCodigo;
    }
    public Set<SegCompania> getSegCompanias() {
        return this.segCompanias;
    }
    
    public void setSegCompanias(Set<SegCompania> segCompanias) {
        this.segCompanias = segCompanias;
    }
    public Set<SegPermiso> getSegPermisosForModUsuCodigo() {
        return this.segPermisosForModUsuCodigo;
    }
    
    public void setSegPermisosForModUsuCodigo(Set<SegPermiso> segPermisosForModUsuCodigo) {
        this.segPermisosForModUsuCodigo = segPermisosForModUsuCodigo;
    }
    public Set<SegSistemaCia> getSegSistemaCias() {
        return this.segSistemaCias;
    }
    
    public void setSegSistemaCias(Set<SegSistemaCia> segSistemaCias) {
        this.segSistemaCias = segSistemaCias;
    }
    public Set<SegPermiso> getSegPermisosForUsuCodigo() {
        return this.segPermisosForUsuCodigo;
    }
    
    public void setSegPermisosForUsuCodigo(Set<SegPermiso> segPermisosForUsuCodigo) {
        this.segPermisosForUsuCodigo = segPermisosForUsuCodigo;
    }
    public Set<SegRolUsuario> getSegRolUsuariosForSegUsuarioUsuCodigo() {
        return this.segRolUsuariosForSegUsuarioUsuCodigo;
    }
    
    public void setSegRolUsuariosForSegUsuarioUsuCodigo(Set<SegRolUsuario> segRolUsuariosForSegUsuarioUsuCodigo) {
        this.segRolUsuariosForSegUsuarioUsuCodigo = segRolUsuariosForSegUsuarioUsuCodigo;
    }
    public Set<SegSistema> getSegSistemas() {
        return this.segSistemas;
    }
    
    public void setSegSistemas(Set<SegSistema> segSistemas) {
        this.segSistemas = segSistemas;
    }
    public Set<SegHistorialConstrasena> getSegHistorialConstrasenas() {
        return this.segHistorialConstrasenas;
    }
    
    public void setSegHistorialConstrasenas(Set<SegHistorialConstrasena> segHistorialConstrasenas) {
        this.segHistorialConstrasenas = segHistorialConstrasenas;
    }
    public Set<SegAuditoria> getSegAuditorias() {
        return this.segAuditorias;
    }
    
    public void setSegAuditorias(Set<SegAuditoria> segAuditorias) {
        this.segAuditorias = segAuditorias;
    }
    public Set<SegOpcion> getSegOpcions() {
        return this.segOpcions;
    }
    
    public void setSegOpcions(Set<SegOpcion> segOpcions) {
        this.segOpcions = segOpcions;
    }
    public Set<SegSucursal> getSegSucursals() {
        return this.segSucursals;
    }
    
    public void setSegSucursals(Set<SegSucursal> segSucursals) {
        this.segSucursals = segSucursals;
    }
    public Set<SegRolUsuario> getSegRolUsuariosForModUsuCodigo() {
        return this.segRolUsuariosForModUsuCodigo;
    }
    
    public void setSegRolUsuariosForModUsuCodigo(Set<SegRolUsuario> segRolUsuariosForModUsuCodigo) {
        this.segRolUsuariosForModUsuCodigo = segRolUsuariosForModUsuCodigo;
    }
    public Set<SegCambioPass> getSegCambioPasses() {
        return this.segCambioPasses;
    }
    
    public void setSegCambioPasses(Set<SegCambioPass> segCambioPasses) {
        this.segCambioPasses = segCambioPasses;
    }
    public Set<SegGrupoOpcion> getSegGrupoOpcions() {
        return this.segGrupoOpcions;
    }
    
    public void setSegGrupoOpcions(Set<SegGrupoOpcion> segGrupoOpcions) {
        this.segGrupoOpcions = segGrupoOpcions;
    }
    public Set<SegUsuario> getSegUsuarios() {
        return this.segUsuarios;
    }
    
    public void setSegUsuarios(Set<SegUsuario> segUsuarios) {
        this.segUsuarios = segUsuarios;
    }
    public Set<SegRol> getSegRols() {
        return this.segRols;
    }
    
    public void setSegRols(Set<SegRol> segRols) {
        this.segRols = segRols;
    }
    public Set<SegParametro> getSegParametros() {
        return this.segParametros;
    }
    
    public void setSegParametros(Set<SegParametro> segParametros) {
        this.segParametros = segParametros;
    }


	public String getUsuPrimerLoginSso() {
		return usuPrimerLoginSso;
	}


	public void setUsuPrimerLoginSso(String usuPrimerLoginSso) {
		this.usuPrimerLoginSso = usuPrimerLoginSso;
	}
    




}


