package com.vortexbird.sentinel.modelo;
// Generated May 21, 2016 6:00:19 PM by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * VinCamposParametrizables generated by hbm2java
 */
public class VinCamposParametrizables  implements java.io.Serializable {


     private String llave;
     private String valor;
     private String operCreador;
     private String operModifica;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private String estadoRegistro;

    public VinCamposParametrizables() {
    }

    public VinCamposParametrizables(String llave, String valor, String operCreador, String operModifica, Date fechaCreacion, Date fechaModificacion, String estadoRegistro) {
       this.llave = llave;
       this.valor = valor;
       this.operCreador = operCreador;
       this.operModifica = operModifica;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.estadoRegistro = estadoRegistro;
    }
   
    public String getLlave() {
        return this.llave;
    }
    
    public void setLlave(String llave) {
        this.llave = llave;
    }
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }
    public String getOperCreador() {
        return this.operCreador;
    }
    
    public void setOperCreador(String operCreador) {
        this.operCreador = operCreador;
    }
    public String getOperModifica() {
        return this.operModifica;
    }
    
    public void setOperModifica(String operModifica) {
        this.operModifica = operModifica;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }




}


